name: GitHub Snake

on:
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run snake
        uses: platane/snk@latest
        with:
          username: giovaleriano
